stages:
  - build
  - test

build-api:
  image: docker:18-git
  stage: build
  services:
    - docker:18-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_BUILD_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - docker
quality-testing:
  stage: test
  script: 
    - sonar-scanner -Dsonar.projectKey=swtp_restapi -Dsonar.sources=. -Dsonar.host.url=https://scm.thm.de/sonar -Dsonar.login=878eff077b2802557f007cf383ad357609befff1
  tags:
    - sonar

